### ISSUE TITLE
Signal6 issue with pattern miner

### ISSUE THREAD

**Issue by DaddyWesker** [opencog/miner#7]
Today i've tried to launch firstly simple example from the site (https://wiki.opencog.org/w/Pattern_miner) and on the line "opencog> loadmodule opencog/learning/PatternMiner/libPatternMinerAgent.so" i've received following output in server's terminal window:

"Listening on port 17001
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /home/cics/OpenCog/opencog/build/../opencog/learning/PatternMiner/ugly_male_soda-drinker_corpus.scm
;;; compiled /home/cics/.cache/guile/ccache/2.0-LE-8-2.0/home/cics/OpenCog/opencog/opencog/learning/PatternMiner/ugly_male_soda-drinker_corpus.scm.go
terminate called after throwing an instance of 'opencog::AssertionException'
  what():   (/home/cics/OpenCog/opencog/opencog/learning/PatternMiner/Parameters.cc:47)
[2018-01-18 10:37:35:266] [ERROR] Caught signal 6 (Aborted) on thread 139683083409472
	Stack Trace:
	2: basic_string.h:539	~basic_string()
	3: CogServerMain.cc:81	_Z7sighandi()
	4: [0x36cb0] ??() ??:0
	5: raise.c:56	__GI_raise()
	6: abort.c:91	__GI_abort()
	7: [0x60535] ??() ??:0
	8: [0x5e6d6] ??() ??:0
	9: [0x5e703] ??() ??:0
	10: [0x5e922] ??() ??:0
	11: oc_assert.cc:59	  opencog::cassert(char const*, bool)
	12: Parameters.cc:47	  opencog::PatternMining::Parameters::reSetAllSettingsFromConfig()
	13: PatternMiner.cc:2682	  opencog::PatternMining::PatternMiner::PatternMiner(opencog::AtomSpace&)
	14: PatternMinerAgent.cc:66	  opencog::PatternMinerAgent::PatternMinerAgent(opencog::CogServer&)
	15: Factory.h:71	  opencog::Factory<opencog::PatternMinerAgent, opencog::Agent>::create(opencog::CogServer&) const
	16: Registry.h:104	  opencog::Registry<opencog::Agent>::create(opencog::CogServer&, std::string const&)
	17: shared_ptr_base.h:448	__shared_count<opencog::Agent*>()
	18: shared_ptr_base.h:545	~__shared_count()
	19: CogServer.cc:481	  opencog::CogServer::loadModule(std::string const&)
	20: LoadModuleRequest.cc:55	  opencog::LoadModuleRequest::execute()
	21: CogServer.cc:261	  opencog::CogServer::processRequests()
	22: CogServer.cc:224	  opencog::CogServer::runLoopStep()
	23: CogServer.cc:199	  opencog::CogServer::serverLoop()
	24: CogServerMain.cc:139	main()
	25: libc-start.c:321	__libc_start_main()
	26: [0x4070fc] ??() ??:0"

Also tried to do similar thing using python's scheme_eval. Like this:

"from opencog.atomspace import AtomSpace, TruthValue
from opencog.atomspace import types
from opencog.type_constructors import *
from opencog.bindlink import satisfying_set, bindlink
from opencog.utilities import initialize_opencog
from opencog.scheme_wrapper import load_scm, scheme_eval, scheme_eval_h

a = AtomSpace()
initialize_opencog(a)
set_type_ctor_atomspace(a)
TV = TruthValue(1, 1)
data = ["opencog/atomspace/core_types.scm",
        "opencog/scm/utilities.scm"]
for item in data:
    load_scm(a, item)
scheme_eval(a, "(add-to-load-path \"/usr/local/share/opencog/scm\")")
scheme_eval(a,"(use-modules (opencog) (opencog nlp) (opencog nlp chatbot) (opencog nlp relex2logic) (opencog atom-types))")
scheme_eval(a,"(use-modules (opencog patternminer))")
scheme_eval(a, "(clear)")
scheme_eval (a,'(load "../opencog/learning/PatternMiner/testdatasmall.scm")')"

and got same signal 6 problem on "scheme_eval(a,"(use-modules (opencog patternminer))")" line. 
"Process finished with exit code 134 (interrupted by signal 6: SIGABRT)"

If anyone could help with that i would really appreciate that. 
Have a nice day!

**Comment by ngeiswei** [comment]
I'm closing, should recreate an issue for the new pattern miner if the problem exists for it.
